# This docker-compose.yml is for devel environment only.
version: '3.4'

services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test

  nginx:
    build:
      context: devops/docker/nginx
      target: devel
    image: dcc-nginx:devel
    volumes:
      - "./src:/var/www"
    ports:
      - "80:80"
    depends_on:
      - php
    links:
      - php:php

  php:
    build:
      context: devops/docker/php
      dockerfile: Dockerfile
      target: devel
    image: dcc-php:devel
    volumes:
      - "./:/var/www"
    depends_on:
      - database
    links:
      - database:database
    environment:
      XDEBUG_CONFIG: remote_host=172.10.0.1 remote_enable=1 remote_autostart=1 remote_log=/tmp/xdebug.log